# Generated by Django 5.2.7 on 2026-08-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100, unique=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('profile_json', models.TextField()),
                ('submissions_json', models.TextField()),
                ('rating_json', models.TextField()),
            ],
        ),
    ]
